# Generated by Django 5.2.1 on 2025-06-03 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade (anos)')),
                ('age_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade (meses)')),
                ('gender', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo')),
                ('size', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1, verbose_name='Porte')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Raça')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('personality', models.TextField(blank=True, verbose_name='Personalidade')),
                ('special_needs', models.TextField(blank=True, verbose_name='Necessidades Especiais')),
                ('photo_url', models.URLField(blank=True, verbose_name='URL da Foto')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('adopted', 'Adotado'), ('pending', 'Adoção Pendente')], default='available', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cão',
                'verbose_name_plural': 'Cães',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito em')),
            ],
            options={
                'verbose_name': 'Inscrição Newsletter',
                'verbose_name_plural': 'Inscrições Newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopter_name', models.CharField(max_length=100, verbose_name='Nome do Adotante')),
                ('dog_name', models.CharField(max_length=100, verbose_name='Nome do Cão')),
                ('testimonial', models.TextField(verbose_name='Depoimento')),
                ('photo_before_url', models.URLField(blank=True, verbose_name='Foto Antes (URL)')),
                ('photo_after_url', models.URLField(blank=True, verbose_name='Foto Depois (URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('age', models.PositiveIntegerField(verbose_name='Idade')),
                ('availability', models.TextField(verbose_name='Disponibilidade')),
                ('skills', models.TextField(verbose_name='Habilidades/Experiência')),
                ('motivation', models.TextField(verbose_name='Por que quer ser voluntário?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Inscrição Voluntário',
                'verbose_name_plural': 'Inscrições Voluntários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('has_experience', models.BooleanField(default=False, verbose_name='Tem experiência com cães?')),
                ('living_situation', models.TextField(verbose_name='Situação de moradia')),
                ('motivation', models.TextField(verbose_name='Por que quer adotar?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dog', verbose_name='Cão')),
            ],
            options={
                'verbose_name': 'Solicitação de Adoção',
                'verbose_name_plural': 'Solicitações de Adoção',
                'ordering': ['-created_at'],
            },
        ),
    ]
